{application,geocalc,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"Calculate distance, bearing and more between latitude/longitude points.\n"},
              {modules,['Elixir.Geocalc','Elixir.Geocalc.Calculator',
                        'Elixir.Geocalc.Calculator.Area',
                        'Elixir.Geocalc.Calculator.Polygon',
                        'Elixir.Geocalc.DMS','Elixir.Geocalc.Point',
                        'Elixir.Geocalc.Point.Geocalc.Shape.Circle',
                        'Elixir.Geocalc.Point.Geocalc.Shape.Ellipse',
                        'Elixir.Geocalc.Point.Geocalc.Shape.Rectangle',
                        'Elixir.Geocalc.Point.List',
                        'Elixir.Geocalc.Point.Map',
                        'Elixir.Geocalc.Point.Tuple','Elixir.Geocalc.Shape',
                        'Elixir.Geocalc.Shape.Circle',
                        'Elixir.Geocalc.Shape.Ellipse',
                        'Elixir.Geocalc.Shape.Rectangle']},
              {registered,[]},
              {vsn,"0.8.4"}]}.
